# Setup
title:        Social Data Analysis and Visualization
tagline:      This took longer to make than it should have
baseurl:      ""
locale:       "en"

# About/contact
author:
  name:       'Laura Paz'
  url:        http://laurapaz.github.io 

# Gems
gems:

#Others
markdown: kramdown
